pub struct UserOptions {
    pub prefix: String,
    pub padding_zeros: i32,
    pub suffix: String,
    pub alpha: f32,
    pub beta: f32,
    pub dm: f32,
    pub min_elem_size: f32,
    pub max_elem_size: f32,
    pub time_step: f32,
    pub max_total_time: f32,
    pub urf_tol: f32,
    pub skip_age: i32,
    pub start_por: f32,
    pub end_por: f32,
    pub delta_por: f32,
    pub is_gather: bool,
    pub calc_decay: bool,
    pub calc_diff: bool,
    pub half_time: f32
}